version: '3.7'

services:

  #####################################################################################
  ldap:
    #####################################################################################
    container_name: ldap
    image: docker.io/petyaba/ldap:1.1.0
    ports:
      - "10389:10389"
    restart: unless-stopped
