version: '3.7'

services:

  #####################################################################################
  ldap:
    #####################################################################################
    container_name: ldap
    image: docker-registry:5000/ldap
    ports:
      - "10389:10389"
    restart: unless-stopped
